import React, { Children } from "react";
export const campaigns = [
  {
    id: "1",
    title: "Clean Water for Rural Communities",
    description:
      "Help us provide clean drinking water to rural communities in need. Your donation will fund well construction and water purification systems.",
    image:
      "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    creator: "Water Aid Foundation",
    goalAmount: 50000,
    raisedAmount: 32450,
    donorCount: 215,
    daysLeft: 12,
    isApproved: true,
    category: "Environment",
    location: "Global",
    createdAt: "2023-09-15",
  },
  {
    id: "2",
    title: "Education for Underprivileged Children",
    description:
      "Support our mission to provide quality education to underprivileged children. Your donation will fund school supplies, teacher salaries, and infrastructure improvements.",
    image:
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1173&q=80",
    creator: "Education First",
    goalAmount: 75000,
    raisedAmount: 45200,
    donorCount: 302,
    daysLeft: 30,
    isApproved: true,
    category: "Education",
    location: "Asia",
    createdAt: "2023-10-05",
  },
  {
    id: "3",
    title: "Emergency Relief for Natural Disaster Victims",
    description:
      "Provide immediate assistance to victims of recent natural disasters. Your donation will help with food, shelter, medical care, and rebuilding efforts.",
    image:
      "https://images.unsplash.com/photo-1603977313771-afd73e18d5a3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    creator: "Global Relief",
    goalAmount: 100000,
    raisedAmount: 87500,
    donorCount: 1240,
    daysLeft: 5,
    isApproved: true,
    category: "Disaster Relief",
    location: "North America",
    createdAt: "2023-11-01",
  },
  {
    id: "4",
    title: "Medical Supplies for Rural Clinics",
    description:
      "Help us provide essential medical supplies to understaffed and under-resourced rural clinics. Your donation will save lives.",
    image:
      "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80",
    creator: "Healthcare for All",
    goalAmount: 30000,
    raisedAmount: 12750,
    donorCount: 85,
    daysLeft: 45,
    isApproved: true,
    category: "Healthcare",
    location: "Africa",
    createdAt: "2023-10-20",
  },
  {
    id: "5",
    title: "Animal Shelter Renovation",
    description:
      "Our animal shelter needs urgent repairs and upgrades to continue providing safe housing for abandoned pets. Help us create a better environment for animals awaiting their forever homes.",
    image:
      "https://images.unsplash.com/photo-1548681528-6a5c45b66b42?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1634&q=80",
    creator: "Animal Rescue League",
    goalAmount: 25000,
    raisedAmount: 8300,
    donorCount: 124,
    daysLeft: 60,
    isApproved: true,
    category: "Animals",
    location: "Europe",
    createdAt: "2023-09-28",
  },
  {
    id: "6",
    title: "Community Garden Project",
    description:
      "Help us transform an empty lot into a thriving community garden that will provide fresh produce and green space for local residents.",
    image:
      "https://images.unsplash.com/photo-1464638681273-0962e9b53566?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    creator: "Green City Initiative",
    goalAmount: 10000,
    raisedAmount: 4200,
    donorCount: 56,
    daysLeft: 25,
    isApproved: false,
    category: "Environment",
    location: "North America",
    createdAt: "2023-10-12",
  },
];
export const pendingCampaigns = [
  {
    id: "7",
    title: "Youth Sports Equipment Drive",
    description:
      "Help us provide sports equipment to underprivileged youth in our community. Your donation will give children the opportunity to participate in team sports.",
    image:
      "https://images.unsplash.com/photo-1526676037777-05a232554f77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
    creator: "Youth Sports Alliance",
    goalAmount: 15000,
    raisedAmount: 0,
    donorCount: 0,
    daysLeft: 90,
    isApproved: false,
    category: "Sports",
    location: "North America",
    createdAt: "2023-11-05",
    status: "pending",
  },
  {
    id: "8",
    title: "Elderly Care Program",
    description:
      "Support our program providing care and companionship to elderly individuals living alone. Your donation will fund home visits, meal delivery, and social activities.",
    image:
      "https://images.unsplash.com/photo-1516307365426-bea591f05011?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    creator: "Elder Care Network",
    goalAmount: 35000,
    raisedAmount: 0,
    donorCount: 0,
    daysLeft: 60,
    isApproved: false,
    category: "Healthcare",
    location: "Europe",
    createdAt: "2023-11-03",
    status: "pending",
  },
];
export const recentDonations = [
  {
    id: "1",
    campaignId: "1",
    amount: 50,
    donor: "John D.",
    isAnonymous: false,
    message: "Keep up the great work!",
    date: "2023-11-07",
  },
  {
    id: "2",
    campaignId: "1",
    amount: 100,
    donor: "Anonymous",
    isAnonymous: true,
    message: "",
    date: "2023-11-06",
  },
  {
    id: "3",
    campaignId: "2",
    amount: 75,
    donor: "Sarah M.",
    isAnonymous: false,
    message: "Education is so important. Happy to help!",
    date: "2023-11-05",
  },
  {
    id: "4",
    campaignId: "3",
    amount: 200,
    donor: "Anonymous",
    isAnonymous: true,
    message: "Praying for everyone affected.",
    date: "2023-11-07",
  },
  {
    id: "5",
    campaignId: "3",
    amount: 500,
    donor: "Robert J.",
    isAnonymous: false,
    message: "Hope this helps with immediate needs.",
    date: "2023-11-06",
  },
];
export const categories = [
  "All Categories",
  "Education",
  "Healthcare",
  "Environment",
  "Disaster Relief",
  "Animals",
  "Arts & Culture",
  "Community Development",
  "Sports",
  "Technology",
  "Other",
];
